[General]
ReportStats = true

[UdpEndpoint main]
Mode = server
Address = 0.0.0.0
Port = 14553
AllowMsgIdOut = 33,32,30
AllowMsgIdIn = ,

[UdpEndpoint broad]
Mode = normal
Address = 192.168.1.255
Port = 14552
# GLOBAL_POSITION_INT, LOCAL_POSITION_NED, ATTITUDE
AllowMsgIdOut = 33,32,30
AllowMsgIdIn = ,